@startuml
right footer FileServer Deployment Diagram

[Application]
[FileServer]
file "file-server.properties" as file.properties
folder FileSystem
database "FileServer\nDatabase" as Database
cloud cloud

Application -right-> FileServer : SOAP/HTTPS
FileServer -up-> file.properties
FileServer -right-> cloud : HTTPS
FileServer --> FileSystem : FILE
FileServer --> Database : JDBC

@enduml