@startuml

[FileServer]
file "file-server.properties" as file.properties
file keystore.p12
file truststore.p12
folder FileSystem
database "FileServer\nDatabase" as Database
cloud cloud

FileServer -left-> file.properties
FileServer -up-> truststore.p12
FileServer -up-> keystore.p12
FileServer -right-> cloud
FileServer --> FileSystem
FileServer --> Database

@enduml